"""
This type stub file was generated by pyright.
"""

import os
import sam2

if os.path.isdir(os.path.join(sam2.__path__[0], "sam2")):
    ...
HF_MODEL_ID_TO_FILENAMES = ...
def build_sam2(config_file, config_dir=..., ckpt_path=..., device=..., mode=..., hydra_overrides_extra=..., apply_postprocessing=..., **kwargs): # -> Any:
    ...

def build_sam2_video_predictor(config_file, config_dir=..., ckpt_path=..., device=..., mode=..., hydra_overrides_extra=..., apply_postprocessing=..., **kwargs): # -> Any:
    ...

def build_sam2_hf(model_id, **kwargs): # -> Any:
    ...

def build_sam2_video_predictor_hf(model_id, **kwargs): # -> Any:
    ...

